import { Exercise, WorkoutTemplate, GymEquipment, Muscle } from './types';

export const DEFAULT_MUSCLES: Muscle[] = [
  { id: 'pecho_superior', name: 'Pecho Superior (Clavicular)', muscle_group: 'chest', svg_target_id: 'chest_upper', description: 'Porción clavicular del pectoral. Clave para aspecto denso y atlético del torso.' },
  { id: 'pecho_medio', name: 'Pecho Medio e Inferior', muscle_group: 'chest', svg_target_id: 'chest_mid', description: 'Porción esternal del pectoral mayor. Da amplitud y grosor frontal.' },
  { id: 'dorsal_ancho', name: 'Dorsales (Latissimus)', muscle_group: 'back', svg_target_id: 'lats', description: 'Músculo principal de la espalda para la forma en V.' },
  { id: 'espalda_alta', name: 'Espalda Alta y Romboides', muscle_group: 'back', svg_target_id: 'upper_back', description: 'Trapecio medio y romboides. Aporta densidad y grosor postural.' },
  { id: 'deltoide_lateral', name: 'Hombro Lateral', muscle_group: 'shoulders', svg_target_id: 'delts_side', description: 'Cabeza lateral del deltoides. Da amplitud visual directa a los hombros.' },
  { id: 'deltoide_anterior', name: 'Hombro Frontal', muscle_group: 'shoulders', svg_target_id: 'delts_front', description: 'Cabeza anterior del deltoides. Activo en empujes.' },
  { id: 'deltoide_posterior', name: 'Hombro Posterior', muscle_group: 'shoulders', svg_target_id: 'delts_rear', description: 'Cabeza posterior del deltoides para aspecto 3D.' },
  { id: 'triceps_larga', name: 'Tríceps (Cabeza Larga)', muscle_group: 'arms', svg_target_id: 'triceps_long', description: 'Masa posterior del brazo, se estimula al estirar overhead.' },
  { id: 'triceps_lateral', name: 'Tríceps (Cabeza Lateral)', muscle_group: 'arms', svg_target_id: 'triceps_lat', description: 'Forma de herradura del tríceps en extensión.' },
  { id: 'biceps', name: 'Bíceps Braquial', muscle_group: 'arms', svg_target_id: 'biceps', description: 'Pico y flexión con supinación de antebrazo.' },
  { id: 'braquial', name: 'Braquial y Antebrazo', muscle_group: 'arms', svg_target_id: 'brachialis', description: 'Empuja el bíceps hacia afuera dando grosor al brazo.' },
  { id: 'cuadriceps', name: 'Cuádriceps', muscle_group: 'legs', svg_target_id: 'quads', description: 'Parte frontal del muslo para extensión de rodilla.' },
  { id: 'isquiosurales', name: 'Isquiosurales (Femoral)', muscle_group: 'legs', svg_target_id: 'hamstrings', description: 'Cadena posterior del muslo, bisagra y flexión.' },
  { id: 'gluteos', name: 'Glúteos', muscle_group: 'legs', svg_target_id: 'glutes', description: 'Mayor generador de fuerza y potencia de cadera.' },
  { id: 'gemelos', name: 'Gemelos / Pantorrillas', muscle_group: 'legs', svg_target_id: 'calves', description: 'Gastrocnemio y sóleo.' },
  { id: 'abdomen', name: 'Abdomen y Core', muscle_group: 'core', svg_target_id: 'abs', description: 'Recto abdominal y estabilización del tronco.' },
];

export const DEFAULT_EQUIPMENT: GymEquipment[] = [
  { id: 'mancuernas', name: 'Mancuernas ajustables o fijas', category: 'Pesas libres', is_default_available: true },
  { id: 'barra_discos', name: 'Barra olímpica y discos', category: 'Pesas libres', is_default_available: true },
  { id: 'banco_ajustable', name: 'Banco ajustable (inclinable / plano)', category: 'Bancos', is_default_available: true },
  { id: 'polea_alta', name: 'Polea alta / Lat Pulldown', category: 'Poleas', is_default_available: true },
  { id: 'polea_baja', name: 'Polea baja / Remo sentado', category: 'Poleas', is_default_available: true },
  { id: 'maquina_smith', name: 'Máquina Smith / Multipower', category: 'Máquinas', is_default_available: true },
  { id: 'prensa_piernas', name: 'Prensa de piernas (45°)', category: 'Máquinas', is_default_available: true },
  { id: 'maquina_ext_cuadriceps', name: 'Máquina de extensión de piernas', category: 'Máquinas', is_default_available: true },
  { id: 'maquina_curl_femoral', name: 'Máquina de curl femoral', category: 'Máquinas', is_default_available: true },
  { id: 'soporte_sentadillas', name: 'Rack / Soporte de sentadillas', category: 'Estructuras', is_default_available: true },
];

export const DEFAULT_EXERCISES: Exercise[] = [
  {
    id: 'press_inclinado_mancuernas',
    name: 'Press Inclinado con Mancuernas',
    short_name: 'Press Inclinado',
    primary_muscle_group: 'chest',
    primary_muscle_id: 'pecho_superior',
    movement_pattern: 'incline_press',
    equipment_id: 'mancuernas',
    difficulty: 'Principiante',
    default_sets: 3,
    rep_range_min: 8,
    rep_range_max: 12,
    default_rir: 2,
    default_rest_sec: 150,
    is_compound: true,
    instructions: 'Banco a unos 30° (2ª o 3ª muesca). Empuja controlando los codos a 45-60 grados del torso.',
    setup: 'Ajusta el banco a 30°. Siéntate con las mancuernas en los muslos y patéalas con las rodillas para subirlas.',
    execution: 'Desciende en 2-3 segundos hasta sentir estiramiento en el pecho alto. Empuja convergiendo ligeramente sin chocar las mancuernas.',
    cues: 'Imagina juntar los bíceps hacia el pecho en la cima.',
    common_errors: 'Inclinación muy alta (>45°), abrir los codos en 90° (peligroso para hombros), rebotar.',
    how_it_should_feel: 'Tensión concentrada debajo de la clavícula en el pecho superior, sin dolor en la parte frontal del hombro.',
    video_url: 'https://www.youtube.com/watch?v=8iPEnn-ltC8',
    gif_url: 'https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0314.gif',
    scientific_note: 'Inclinación de 30° maximiza la electromiografía (EMG) del haz clavicular minimizando la activación excesiva del deltoides anterior (investigaciones de Trebs et al. y Jeff Nippard).',
    why_this_exercise: 'Es el mejor ejercicio constructor de la parte superior del pecho para crear el torso atlético y estético.',
    ranking_tier: 'S',
    primary_muscles: ['pecho_superior'],
    secondary_muscles: ['deltoide_anterior', 'triceps_lateral']
  },
  {
    id: 'remo_mancuerna_pecho_apoyado',
    name: 'Remo con Pecho Apoyado en Banco Inclinado',
    short_name: 'Remo Pecho Apoyado',
    primary_muscle_group: 'back',
    primary_muscle_id: 'espalda_alta',
    movement_pattern: 'horizontal_row',
    equipment_id: 'banco_ajustable',
    difficulty: 'Principiante',
    default_sets: 3,
    rep_range_min: 8,
    rep_range_max: 12,
    default_rir: 2,
    default_rest_sec: 150,
    is_compound: true,
    instructions: 'Acuéstate boca abajo sobre el banco inclinado a 30-45°. Tira de las mancuernas liderando con los codos hacia atrás.',
    setup: 'Pecho firme sobre la almohadilla, barbilla neutra, brazos extendidos sosteniendo las mancuernas.',
    execution: 'Tira de los codos hacia atrás en ángulo de 45-60°, aprieta las escápulas 1 segundo arriba y desciende en 2 segundos.',
    cues: 'Piensa en pellizcar una moneda entre tus escápulas con los codos.',
    common_errors: 'Despegar el pecho del banco por usar demasiado peso, encoger hombros hacia las orejas.',
    how_it_should_feel: 'Contracción y ardor limpio en el centro y parte alta de la espalda sin tensión lumbar.',
    video_url: 'https://www.youtube.com/watch?v=H75im9fAUMc',
    gif_url: 'https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0327.gif',
    scientific_note: 'Al apoyar el pecho, se elimina la fatiga de los erectores espinales, permitiendo que el 100% del estímulo vaya al romboides, trapecio medio y dorsal con máximo ratio estímulo/fatiga.',
    why_this_exercise: 'Ideal para principiantes: previene lesiones lumbares y enseña a tirar correctamente con la espalda.',
    ranking_tier: 'S',
    primary_muscles: ['espalda_alta'],
    secondary_muscles: ['dorsal_ancho', 'deltoide_posterior', 'biceps']
  },
  {
    id: 'jalon_pecho_agarre_neutro',
    name: 'Jalón al Pecho con Agarre Neutro',
    short_name: 'Jalón Neutro',
    primary_muscle_group: 'back',
    primary_muscle_id: 'dorsal_ancho',
    movement_pattern: 'vertical_pull',
    equipment_id: 'polea_alta',
    difficulty: 'Principiante',
    default_sets: 3,
    rep_range_min: 8,
    rep_range_max: 12,
    default_rir: 2,
    default_rest_sec: 120,
    is_compound: true,
    instructions: 'Palmas enfrentadas (agarre neutro). Inclina el torso unos 10-15° y tira la barra hacia la parte alta del esternón.',
    setup: 'Muslos asegurados bajo las almohadillas para no levantarse del asiento.',
    execution: 'Tira llevando los codos rectos hacia el suelo y las costillas. Controla la subida sintiendo estiramiento bajo las axilas.',
    cues: 'Guarda los codos en los bolsillos del pantalón.',
    common_errors: 'Tirarse hacia atrás con inercia para mover la carga, jalar detrás de la nuca.',
    how_it_should_feel: 'Estiramiento profundo y contracción intensa debajo de las axilas y en los costados.',
    video_url: 'https://www.youtube.com/watch?v=CAwf7n6Luuc',
    gif_url: 'https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0818.gif',
    scientific_note: 'El agarre neutro coloca al hombro en una posición biomecánicamente óptima y segura para la trayectoria sagital del dorsal ancho.',
    why_this_exercise: 'Clave para ensanchar la espalda y generar la silueta en V.',
    ranking_tier: 'S',
    primary_muscles: ['dorsal_ancho'],
    secondary_muscles: ['biceps', 'espalda_alta']
  },
  {
    id: 'elevaciones_laterales_polea',
    name: 'Elevaciones Laterales en Polea (o Mancuernas)',
    short_name: 'Elevaciones Laterales',
    primary_muscle_group: 'shoulders',
    primary_muscle_id: 'deltoide_lateral',
    movement_pattern: 'isolation',
    equipment_id: 'polea_baja',
    difficulty: 'Principiante',
    default_sets: 3,
    rep_range_min: 10,
    rep_range_max: 15,
    default_rir: 1,
    default_rest_sec: 90,
    is_compound: false,
    instructions: 'Polea a la altura de la rodilla o muñeca. Eleva el brazo en el plano escapular (20-30° hacia adelante del cuerpo) hasta la altura del hombro.',
    setup: 'Cuerpo ligeramente inclinado hacia el lado de trabajo para alinear la línea de fuerza.',
    execution: 'Eleva el brazo guiando con el codo. Pausa un instante a la altura paralela y baja despacio.',
    cues: 'Lanza las manos hacia las paredes laterales, no hacia el techo.',
    common_errors: 'Usar impulso de piernas, subir por encima del hombro involucrando el trapecio alto.',
    how_it_should_feel: 'Ardor focalizado exactamente en la cara lateral del hombro.',
    video_url: 'https://www.youtube.com/watch?v=PPrzBWZDOhA',
    gif_url: 'https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0178.gif',
    scientific_note: 'La polea mantiene tensión constante durante todo el recorrido, especialmente en el estiramiento donde las mancuernas pierden resistencia.',
    why_this_exercise: 'El ejercicio número 1 indiscutible para hombros anchos y silueta en V.',
    ranking_tier: 'S',
    primary_muscles: ['deltoide_lateral'],
    secondary_muscles: ['deltoide_posterior']
  },
  {
    id: 'curl_biceps_inclinado',
    name: 'Curl de Bíceps en Banco Inclinado',
    short_name: 'Curl Inclinado',
    primary_muscle_group: 'arms',
    primary_muscle_id: 'biceps',
    movement_pattern: 'isolation',
    equipment_id: 'banco_ajustable',
    difficulty: 'Principiante',
    default_sets: 3,
    rep_range_min: 10,
    rep_range_max: 12,
    default_rir: 2,
    default_rest_sec: 90,
    is_compound: false,
    instructions: 'Banco a 60°. Siéntate con los brazos colgando verticalmente detrás del torso. Flexiona supinando las muñecas arriba.',
    setup: 'Hombros relajados hacia atrás, brazos colgando detrás del torso para enfatizar el estiramiento.',
    execution: 'Sube las mancuernas girando las palmas al techo sin adelantar los codos. Desciende lento estirando el bíceps abajo.',
    cues: 'Gira el meñique hacia arriba en la cima de la contracción.',
    common_errors: 'Balancear el cuerpo para subir las mancuernas, despegar la espalda del banco.',
    how_it_should_feel: 'Tensión extrema en la cabeza larga del bíceps desde el estiramiento profundo.',
    video_url: 'https://www.youtube.com/watch?v=soxrZlIl35U',
    gif_url: 'https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0318.gif',
    scientific_note: 'Proporciona hipertrofia mediada por estiramiento de la cabeza larga del bíceps al colocar el hombro en hiperextensión pasiva.',
    why_this_exercise: 'Desarrolla el pico y relieve del bíceps de forma rápida y medible.',
    ranking_tier: 'A',
    primary_muscles: ['biceps'],
    secondary_muscles: ['braquial']
  },
  {
    id: 'extension_triceps_overhead_polea',
    name: 'Extensión de Tríceps Overhead en Polea',
    short_name: 'Extensión Tríceps Overhead',
    primary_muscle_group: 'arms',
    primary_muscle_id: 'triceps_larga',
    movement_pattern: 'isolation',
    equipment_id: 'polea_alta',
    difficulty: 'Principiante',
    default_sets: 3,
    rep_range_min: 10,
    rep_range_max: 15,
    default_rir: 2,
    default_rest_sec: 90,
    is_compound: false,
    instructions: 'De espaldas a la polea con cuerda. Con codos fijos junto a las orejas, extiende hacia adelante separando la cuerda.',
    setup: 'Torso inclinado a 45°, codos estables apuntando al frente, cuerda sostenida detrás de la cabeza.',
    execution: 'Extiende los codos por completo abriendo la cuerda al final. Vuelve sintiendo el estiramiento en la parte posterior del brazo.',
    cues: 'Bloquea los codos en el espacio y muévete solo desde el antebrazo.',
    common_errors: 'Mover los hombros durante el recorrido transformándolo en un press con impulso.',
    how_it_should_feel: 'Estiramiento y quemazón intensa en la parte interna y trasera del brazo.',
    video_url: 'https://www.youtube.com/watch?v=1u18yJmLrTc',
    gif_url: 'https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0194.gif',
    scientific_note: 'La cabeza larga del tríceps solo se coloca en estiramiento completo cuando el brazo está elevado sobre la cabeza.',
    why_this_exercise: 'Construye los dos tercios del volumen total del brazo.',
    ranking_tier: 'S',
    primary_muscles: ['triceps_larga'],
    secondary_muscles: ['triceps_lateral']
  },
  {
    id: 'prensa_piernas_45',
    name: 'Prensa de Piernas a 45°',
    short_name: 'Prensa 45°',
    primary_muscle_group: 'legs',
    primary_muscle_id: 'cuadriceps',
    movement_pattern: 'squat',
    equipment_id: 'prensa_piernas',
    difficulty: 'Principiante',
    default_sets: 3,
    rep_range_min: 8,
    rep_range_max: 12,
    default_rir: 2,
    default_rest_sec: 180,
    is_compound: true,
    instructions: 'Pies al ancho de hombros en el centro de la plataforma. Baja hasta 90° o más sin que los glúteos se despeguen del respaldo.',
    setup: 'Espalda baja pegada al respaldo, manos sujetando con fuerza las manijas para anclar la pelvis.',
    execution: 'Baja en 3 segundos controlados. Empuja con toda la planta del pie extendiendo sin bloquear bruscamente las rodillas arriba.',
    cues: 'Tira de las manijas hacia ti para aplastar la cadera contra el asiento.',
    common_errors: 'Despegar el coxis del respaldo (peligroso para la columna lumbar), dejar caer las rodillas hacia adentro.',
    how_it_should_feel: 'Quema profunda en los muslos sin presión en las lumbares.',
    video_url: 'https://www.youtube.com/watch?v=IZxyjW7MPJQ',
    gif_url: 'https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0739.gif',
    scientific_note: 'Alta estabilidad externa comparada con sentadillas libres, permitiendo llegar a RIR 1-2 con máxima seguridad.',
    why_this_exercise: 'Base de fuerza e hipertrofia de piernas con mínimo riesgo de lesión técnica.',
    ranking_tier: 'S',
    primary_muscles: ['cuadriceps'],
    secondary_muscles: ['gluteos']
  },
  {
    id: 'peso_muerto_rumano_mancuernas',
    name: 'Peso Muerto Rumano con Mancuernas (RDL)',
    short_name: 'RDL Mancuernas',
    primary_muscle_group: 'legs',
    primary_muscle_id: 'isquiosurales',
    movement_pattern: 'hinge',
    equipment_id: 'mancuernas',
    difficulty: 'Principiante',
    default_sets: 3,
    rep_range_min: 8,
    rep_range_max: 10,
    default_rir: 2,
    default_rest_sec: 150,
    is_compound: true,
    instructions: 'Rodillas con flexión ligera fija. Empuja la cadera hacia atrás como si quisieras tocar una pared con los glúteos, bajando mancuernas pegadas.',
    setup: 'Pies al ancho de cadera, pecho erguido, mirada en diagonal al suelo para cuello neutro.',
    execution: 'Desciende hasta donde tu flexibilidad lo permita sin arquear la espalda. Contrae glúteos para volver arriba.',
    cues: 'Empuja la pelvis hacia atrás, no pienses en bajar las pesas al suelo sino en llevar el trasero atrás.',
    common_errors: 'Agachar las piernas en sentadilla, doblar la columna por intentar tocar el piso.',
    how_it_should_feel: 'Estiramiento y tensión fuerte en la parte trasera de los muslos y glúteos.',
    video_url: 'https://www.youtube.com/watch?v=JCXUYuzwNrM',
    gif_url: 'https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/1459.gif',
    scientific_note: 'Entrena los isquiosurales y glúteos en su posición más hipertrófica (estiramiento excéntrico bajo carga).',
    why_this_exercise: 'El mejor constructor de la cadena posterior y postura.',
    ranking_tier: 'S',
    primary_muscles: ['isquiosurales'],
    secondary_muscles: ['gluteos']
  },
  {
    id: 'extension_piernas_maquina',
    name: 'Extensión de Piernas en Máquina',
    short_name: 'Extensión Cuádriceps',
    primary_muscle_group: 'legs',
    primary_muscle_id: 'cuadriceps',
    movement_pattern: 'isolation',
    equipment_id: 'maquina_ext_cuadriceps',
    difficulty: 'Principiante',
    default_sets: 3,
    rep_range_min: 10,
    rep_range_max: 15,
    default_rir: 1,
    default_rest_sec: 90,
    is_compound: false,
    instructions: 'Alinea las rodillas con el eje de la máquina. Extiende las piernas hasta la horizontal, aprieta 1s y baja en 2s.',
    setup: 'Sujétate con fuerza de las manijas para que los glúteos no se despeguen al patear.',
    execution: 'Sube de forma fluida, aguanta 1 segundo arriba apretando los cuádriceps y baja en 2 segundos.',
    cues: 'Extiende apretando la rótula hacia arriba.',
    common_errors: 'Impulsarse despegando la cadera, dejar caer el peso de golpe al bajar.',
    how_it_should_feel: 'Ardor puro en la cara frontal y media de los muslos.',
    video_url: 'https://www.youtube.com/watch?v=YyvSfVjQeL0',
    gif_url: 'https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0585.gif',
    scientific_note: 'Aísla de forma óptima el recto femoral del cuádriceps que no recibe estímulo completo en sentadillas.',
    why_this_exercise: 'Añade relieve y separación al muslo frontal sin fatiga de espalda.',
    ranking_tier: 'S',
    primary_muscles: ['cuadriceps'],
    secondary_muscles: []
  },
  {
    id: 'curl_femoral_tumbado',
    name: 'Curl Femoral en Máquina (Tumbado o Sentado)',
    short_name: 'Curl Femoral',
    primary_muscle_group: 'legs',
    primary_muscle_id: 'isquiosurales',
    movement_pattern: 'isolation',
    equipment_id: 'maquina_curl_femoral',
    difficulty: 'Principiante',
    default_sets: 3,
    rep_range_min: 10,
    rep_range_max: 12,
    default_rir: 1,
    default_rest_sec: 90,
    is_compound: false,
    instructions: 'Rodillo sobre los talones. Flexiona las rodillas llevando los talones hacia los glúteos manteniendo la pelvis pegada.',
    setup: 'Alinea la articulación de la rodilla con el eje de giro de la máquina.',
    execution: 'Tira fuerte con los talones, mantén un segundo la contracción máxima y baja controlando.',
    cues: 'Empuja la pelvis contra el banco mientras flexionas las piernas.',
    common_errors: 'Arquear la espalda lumbar para compensar el peso.',
    how_it_should_feel: 'Contracción profunda en la curva posterior de la rodilla y muslo.',
    video_url: 'https://www.youtube.com/watch?v=ELOCsoDSmrg',
    gif_url: 'https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0586.gif',
    scientific_note: 'Estimula los isquiosurales a través de la flexión de rodilla, complementando al RDL.',
    why_this_exercise: 'Protege las rodillas y balancea la masa muscular de las piernas.',
    ranking_tier: 'S',
    primary_muscles: ['isquiosurales'],
    secondary_muscles: []
  },
  {
    id: 'elevacion_talones_gemelos',
    name: 'Elevación de Talones para Gemelos',
    short_name: 'Elevación Gemelos',
    primary_muscle_group: 'legs',
    primary_muscle_id: 'gemelos',
    movement_pattern: 'isolation',
    equipment_id: 'prensa_piernas',
    difficulty: 'Principiante',
    default_sets: 3,
    rep_range_min: 12,
    rep_range_max: 15,
    default_rir: 1,
    default_rest_sec: 60,
    is_compound: false,
    instructions: 'Pies sobre el borde con rodillas rectas. Baja los talones hasta el estiramiento completo durante 2 segundos y eleva sobre las puntas.',
    setup: 'Apoyo firme sobre el metatarso con rango libre hacia abajo.',
    execution: 'Pausa de 2 segundos en el fondo para disipar el rebote elástico del tendón de Aquiles, eleva y aprieta.',
    cues: 'Quédate quieto 2 segundos en el estiramiento profundo abajo.',
    common_errors: 'Rebotar rápido como resorte sin trabajar el músculo.',
    how_it_should_feel: 'Quemazón concentrada en la pantorrilla.',
    video_url: 'https://www.youtube.com/watch?v=gwLzBJYoWlI',
    gif_url: 'https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/1379.gif',
    scientific_note: 'La pausa en el fondo elimina el reflejo miotático y la energía elástica del tendón de Aquiles, obligando al gastrocnemio al esfuerzo.',
    why_this_exercise: 'Asegura crecimiento real en pantorrillas.',
    ranking_tier: 'A',
    primary_muscles: ['gemelos'],
    secondary_muscles: []
  },
  {
    id: 'plank_o_cable_woodchopper',
    name: 'Plancha Abdominal Estricta o Antirrotación',
    short_name: 'Plancha Abdominal',
    primary_muscle_group: 'core',
    primary_muscle_id: 'abdomen',
    movement_pattern: 'isolation',
    equipment_id: 'mancuernas',
    difficulty: 'Principiante',
    default_sets: 3,
    rep_range_min: 30,
    rep_range_max: 45,
    default_rir: 1,
    default_rest_sec: 60,
    is_compound: false,
    instructions: 'Apoyo sobre antebrazos y pies. Cuerpo recto como una tabla apretando glúteos y metiendo el ombligo.',
    setup: 'Codos debajo de hombros, mirada al suelo entre brazos.',
    execution: 'Tensa activamente el abdomen como si fueras a recibir un golpe. Respira controlado.',
    cues: 'Tira de los codos hacia los pies para tensión isométrica máxima.',
    common_errors: 'Dejar caer la cadera hacia el piso o subir el trasero.',
    how_it_should_feel: 'Abdomen de piedra y cintura compacta.',
    video_url: 'https://www.youtube.com/watch?v=ASdvN_XEl_c',
    gif_url: 'https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0464.gif',
    scientific_note: 'Fortalece el transverso y recto abdominal mediante resistencia isométrica a la extensión.',
    why_this_exercise: 'Cintura compacta y soporte para todos los ejercicios.',
    ranking_tier: 'A',
    primary_muscles: ['abdomen'],
    secondary_muscles: []
  },
  {
    id: 'press_plano_mancuernas',
    name: 'Press de Banca Plano con Mancuernas o Smith',
    short_name: 'Press Plano Mancuernas',
    primary_muscle_group: 'chest',
    primary_muscle_id: 'pecho_medio',
    movement_pattern: 'horizontal_press',
    equipment_id: 'mancuernas',
    difficulty: 'Principiante',
    default_sets: 3,
    rep_range_min: 8,
    rep_range_max: 12,
    default_rir: 2,
    default_rest_sec: 150,
    is_compound: true,
    instructions: 'Banco plano, escápulas retraídas. Baja controlando las mancuernas al pecho medio y presiona arriba.',
    setup: 'Pecho alto, escápulas retraídas, codos en 45° respecto al cuerpo.',
    execution: 'Baja en 2-3 segundos sintiendo el estiramiento. Empuja convergiendo ligeramente.',
    cues: 'Imagina que juntas los codos hacia el centro del pecho.',
    common_errors: 'Codos abiertos en T a 90° (daña el hombro), levantar la cabeza.',
    how_it_should_feel: 'Activación plena en el centro y base del pectoral.',
    video_url: 'https://www.youtube.com/watch?v=VmB1G1K7v94',
    gif_url: 'https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0289.gif',
    scientific_note: 'Mayor rango de movimiento y convergencia natural de muñecas respecto a la barra fija.',
    why_this_exercise: 'Excelente constructor de masa pectoral global.',
    ranking_tier: 'S',
    primary_muscles: ['pecho_medio'],
    secondary_muscles: ['deltoide_anterior', 'triceps_lateral']
  },
  {
    id: 'remo_polea_baja_neutro',
    name: 'Remo Sentado en Polea Baja con Agarre Neutro',
    short_name: 'Remo Polea Baja',
    primary_muscle_group: 'back',
    primary_muscle_id: 'dorsal_ancho',
    movement_pattern: 'horizontal_row',
    equipment_id: 'polea_baja',
    difficulty: 'Principiante',
    default_sets: 3,
    rep_range_min: 8,
    rep_range_max: 12,
    default_rir: 2,
    default_rest_sec: 120,
    is_compound: true,
    instructions: 'Maneral estrecho o neutro. Torso vertical, tira hacia el ombligo llevando los codos pegados al cuerpo.',
    setup: 'Columna neutra, hombros abajo y hacia atrás.',
    execution: 'Inicia con leve inclinación al frente para estirar el dorsal, luego tira con codos rozando los costados.',
    cues: 'Maneja el peso con los codos como pistones pegados a las costillas.',
    common_errors: 'Columpiar la espalda hacia atrás en cada repetición por usar peso excesivo.',
    how_it_should_feel: 'Presión y congestión limpia en los costados de la espalda y dorsales bajos.',
    video_url: 'https://www.youtube.com/watch?v=GZbfZ033f74',
    gif_url: 'https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0180.gif',
    scientific_note: 'El ángulo horizontal bajo con codos pegados recluta las fibras lumbares e iliocostales del dorsal.',
    why_this_exercise: 'Favorece la silueta en V desde la cintura hacia arriba.',
    ranking_tier: 'S',
    primary_muscles: ['dorsal_ancho'],
    secondary_muscles: ['espalda_alta', 'biceps']
  },
  {
    id: 'pullover_polea_alta',
    name: 'Pullover en Polea Alta con Cuerda o Barra',
    short_name: 'Pullover Polea',
    primary_muscle_group: 'back',
    primary_muscle_id: 'dorsal_ancho',
    movement_pattern: 'isolation',
    equipment_id: 'polea_alta',
    difficulty: 'Principiante',
    default_sets: 3,
    rep_range_min: 10,
    rep_range_max: 15,
    default_rir: 1,
    default_rest_sec: 90,
    is_compound: false,
    instructions: 'Torso inclinado 30-45°, brazos casi rectos con ligera flexión fija. Lleva el accesorio hacia tus muslos en un arco amplio.',
    setup: 'Brazos extendidos al frente a la altura de la vista, pecho erguido, core firme.',
    execution: 'Lleva el accesorio a tus caderas. Aprieta los dorsales 1 segundo y regresa sintiendo el estiramiento arriba.',
    cues: 'Empuja hacia abajo barriendo con las manos hacia tus bolsillos.',
    common_errors: 'Doblar y estirar los codos convirtiéndolo en tríceps, impulsarse con el cuerpo.',
    how_it_should_feel: 'Tensión pura en los costados de la espalda sin fatiga de bíceps.',
    video_url: 'https://www.youtube.com/watch?v=cM3yP-mI0tY',
    gif_url: 'https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0199.gif',
    scientific_note: 'Aísla el dorsal ancho en extensión de hombro eliminando el límite de cansancio del bíceps.',
    why_this_exercise: 'Máximo estímulo de ensanchamiento con cero impacto en muñecas o lumbares.',
    ranking_tier: 'A',
    primary_muscles: ['dorsal_ancho'],
    secondary_muscles: ['triceps_larga']
  },
  {
    id: 'triceps_pushdown_polea_cuerda',
    name: 'Extensiones de Tríceps en Polea con Cuerda',
    short_name: 'Tríceps Cuerda',
    primary_muscle_group: 'arms',
    primary_muscle_id: 'triceps_lateral',
    movement_pattern: 'isolation',
    equipment_id: 'polea_alta',
    difficulty: 'Principiante',
    default_sets: 3,
    rep_range_min: 10,
    rep_range_max: 15,
    default_rir: 1,
    default_rest_sec: 90,
    is_compound: false,
    instructions: 'Codos pegados a los costados. Extiende los antebrazos hacia abajo separando la cuerda al final.',
    setup: 'Codos fijos como bisagras a los lados del torso.',
    execution: 'Extiende hasta el bloqueo abriendo las muñecas. Regresa hasta que los antebrazos queden paralelos al piso.',
    cues: 'Abre la cuerda hacia tus muslos en la parte inferior.',
    common_errors: 'Dejar que los codos viajen hacia adelante y atrás.',
    how_it_should_feel: 'Aprete directo en la parte externa del brazo.',
    video_url: 'https://www.youtube.com/watch?v=vB5OHsJ3EME',
    gif_url: 'https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0200.gif',
    scientific_note: 'La separación de cuerda al final permite contracción máxima de las cabezas lateral y medial.',
    why_this_exercise: 'Moldea la forma de herradura del brazo.',
    ranking_tier: 'A',
    primary_muscles: ['triceps_lateral'],
    secondary_muscles: ['triceps_larga']
  },
  {
    id: 'curl_martillo_mancuernas',
    name: 'Curl Martillo con Mancuernas',
    short_name: 'Curl Martillo',
    primary_muscle_group: 'arms',
    primary_muscle_id: 'braquial',
    movement_pattern: 'isolation',
    equipment_id: 'mancuernas',
    difficulty: 'Principiante',
    default_sets: 3,
    rep_range_min: 10,
    rep_range_max: 12,
    default_rir: 2,
    default_rest_sec: 90,
    is_compound: false,
    instructions: 'Palmas enfrentadas (agarre neutro). Sube las mancuernas con los pulgares hacia arriba sin rotar muñecas.',
    setup: 'Tronco erguido, hombros encajados atrás, codos fijos a los lados.',
    execution: 'Sube la mancuerna manteniendo el pulgar arriba. Aprieta arriba y baja controlando en 2 segundos.',
    cues: 'Imagina martillar un clavo con la cabeza frontal de la mancuerna.',
    common_errors: 'Balancear el torso o subir los codos hacia adelante.',
    how_it_should_feel: 'Sensación de trabajo en el antebrazo y cara lateral del brazo entre bíceps y tríceps.',
    video_url: 'https://www.youtube.com/watch?v=zC3nLlEvin4',
    gif_url: 'https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0313.gif',
    scientific_note: 'El agarre neutro coloca al bíceps en desventaja mecánica y transfiere la carga al músculo braquial.',
    why_this_exercise: 'Empuja el bíceps hacia arriba haciendo que el brazo se vea mucho más grueso de frente.',
    ranking_tier: 'S',
    primary_muscles: ['braquial'],
    secondary_muscles: ['biceps']
  },
  {
    id: 'sentadilla_bulgara_mancuernas',
    name: 'Sentadilla Búlgara con Mancuernas',
    short_name: 'Sentadilla Búlgara',
    primary_muscle_group: 'legs',
    primary_muscle_id: 'cuadriceps',
    movement_pattern: 'squat',
    equipment_id: 'mancuernas',
    difficulty: 'Principiante',
    default_sets: 3,
    rep_range_min: 8,
    rep_range_max: 10,
    default_rir: 2,
    default_rest_sec: 120,
    is_compound: true,
    instructions: 'Empeine apoyado en banco trasero. Baja la cadera flexionando la pierna delantera hasta que el muslo quede casi paralelo al piso.',
    setup: 'Torso con ligera inclinación de 15° para repartir carga entre cuádriceps y glúteo.',
    execution: 'Desciende en línea recta controlando la rodilla delantera. Presiona a través del talón y medio pie.',
    cues: 'Baja la rodilla trasera hacia el suelo como si fueras a arrodillarte suavemente.',
    common_errors: 'Paso demasiado corto o tambalearse por no fijar la vista en un punto.',
    how_it_should_feel: 'Trabajo profundo y exigente en cuádriceps y glúteo de la pierna delantera.',
    video_url: 'https://www.youtube.com/watch?v=2C-uNgKwPLE',
    gif_url: 'https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0410.gif',
    scientific_note: 'Corrige asimetrías de fuerza entre piernas y ofrece alto estímulo con mínima carga espinal.',
    why_this_exercise: 'Excelente desarrollo muscular de piernas y glúteos con mancuernas básicas.',
    ranking_tier: 'S',
    primary_muscles: ['cuadriceps'],
    secondary_muscles: ['gluteos']
  },
  {
    id: 'elevacion_piernas_colgado_o_banco',
    name: 'Elevación de Piernas o Rodillas en Banco / Barra',
    short_name: 'Elevación de Piernas',
    primary_muscle_group: 'core',
    primary_muscle_id: 'abdomen',
    movement_pattern: 'isolation',
    equipment_id: 'banco_ajustable',
    difficulty: 'Principiante',
    default_sets: 3,
    rep_range_min: 10,
    rep_range_max: 15,
    default_rir: 1,
    default_rest_sec: 60,
    is_compound: false,
    instructions: 'Acuéstate en el banco sujetando la parte superior. Eleva las piernas enrollando la pelvis hacia el ombligo al final.',
    setup: 'Espalda baja pegada al banco al inicio.',
    execution: 'Sube las rodillas/piernas y levanta ligeramente la pelvis del banco al final para contraer el recto abdominal inferior.',
    cues: 'Enrolla la pelvis hacia tu pecho, no solo muevas las piernas.',
    common_errors: 'Arquear la espalda al bajar transfiriendo tensión al psoas.',
    how_it_should_feel: 'Quemazón concentrada en la porción inferior del abdomen.',
    video_url: 'https://www.youtube.com/watch?v=hdng3Nm1x_E',
    gif_url: 'https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/0472.gif',
    scientific_note: 'La retroversión pélvica al final garantiza la activación mecánica del recto abdominal.',
    why_this_exercise: 'Cintura estética y compacta.',
    ranking_tier: 'A',
    primary_muscles: ['abdomen'],
    secondary_muscles: []
  }
];

export const DEFAULT_TEMPLATES: WorkoutTemplate[] = [
  {
    id: 'template_upper_a',
    name: 'Upper A (Torso Enfoque Densidad & V-Taper)',
    code: 'upper_a',
    sequence_order: 1,
    target_focus: 'Pecho Superior, Espalda Alta, Hombro Lateral, Brazos',
    estimated_duration_min: 55,
    description: 'Sesión centrada en crear hombros anchos y torso atlético con máxima relación estímulo/fatiga.',
    warmup_cardio_min: 5,
    warmup_mobility: 'Círculos dinámicos de brazos, retracciones escapulares en pared, dislocaciones con banda o pica.',
    exercises: [
      { id: 'u1', template_id: 'template_upper_a', exercise_id: 'press_inclinado_mancuernas', order_index: 1, target_sets: 3, target_reps_min: 8, target_reps_max: 12, target_rir: 2, target_rest_sec: 150, priority: 'high', warmup_feeder_sets: 2, special_notes: 'Haz 2 series de calentamiento/aproximación con 40% y 70% de carga.' },
      { id: 'u2', template_id: 'template_upper_a', exercise_id: 'remo_mancuerna_pecho_apoyado', order_index: 2, target_sets: 3, target_reps_min: 8, target_reps_max: 12, target_rir: 2, target_rest_sec: 150, priority: 'high', warmup_feeder_sets: 1, special_notes: '1 serie ligera de aproximación.' },
      { id: 'u3', template_id: 'template_upper_a', exercise_id: 'jalon_pecho_agarre_neutro', order_index: 3, target_sets: 3, target_reps_min: 8, target_reps_max: 12, target_rir: 2, target_rest_sec: 120, priority: 'high', warmup_feeder_sets: 0, special_notes: 'Pasa directo a series efectivas.' },
      { id: 'u4', template_id: 'template_upper_a', exercise_id: 'elevaciones_laterales_polea', order_index: 4, target_sets: 3, target_reps_min: 10, target_reps_max: 15, target_rir: 1, target_rest_sec: 90, priority: 'medium', warmup_feeder_sets: 0 },
      { id: 'u5', template_id: 'template_upper_a', exercise_id: 'curl_biceps_inclinado', order_index: 5, target_sets: 3, target_reps_min: 10, target_reps_max: 12, target_rir: 2, target_rest_sec: 90, priority: 'low', warmup_feeder_sets: 0 },
      { id: 'u6', template_id: 'template_upper_a', exercise_id: 'extension_triceps_overhead_polea', order_index: 6, target_sets: 3, target_reps_min: 10, target_reps_max: 15, target_rir: 2, target_rest_sec: 90, priority: 'low', warmup_feeder_sets: 0 },
    ]
  },
  {
    id: 'template_lower_a',
    name: 'Lower A (Pierna Cuádriceps & Cadena Posterior)',
    code: 'lower_a',
    sequence_order: 2,
    target_focus: 'Cuádriceps en Prensa, Isquios en RDL, Pantorrillas y Core',
    estimated_duration_min: 50,
    description: 'Desarrollo balanceado de piernas sin sobrecargar la espalda baja.',
    warmup_cardio_min: 5,
    warmup_mobility: 'Movilidad de tobillo contra pared, apertura de cadera 90/90, sentadillas corporales dinámicas.',
    exercises: [
      { id: 'l1', template_id: 'template_lower_a', exercise_id: 'prensa_piernas_45', order_index: 1, target_sets: 3, target_reps_min: 8, target_reps_max: 12, target_rir: 2, target_rest_sec: 180, priority: 'high', warmup_feeder_sets: 2, special_notes: '2 series de aproximación con el carro vacío o 50% de carga.' },
      { id: 'l2', template_id: 'template_lower_a', exercise_id: 'peso_muerto_rumano_mancuernas', order_index: 2, target_sets: 3, target_reps_min: 8, target_reps_max: 10, target_rir: 2, target_rest_sec: 150, priority: 'high', warmup_feeder_sets: 1, special_notes: '1 serie de calentamiento con mancuernas livianas.' },
      { id: 'l3', template_id: 'template_lower_a', exercise_id: 'extension_piernas_maquina', order_index: 3, target_sets: 3, target_reps_min: 10, target_reps_max: 15, target_rir: 1, target_rest_sec: 90, priority: 'medium', warmup_feeder_sets: 0 },
      { id: 'l4', template_id: 'template_lower_a', exercise_id: 'curl_femoral_tumbado', order_index: 4, target_sets: 3, target_reps_min: 10, target_reps_max: 12, target_rir: 1, target_rest_sec: 90, priority: 'medium', warmup_feeder_sets: 0 },
      { id: 'l5', template_id: 'template_lower_a', exercise_id: 'elevacion_talones_gemelos', order_index: 5, target_sets: 3, target_reps_min: 12, target_reps_max: 15, target_rir: 1, target_rest_sec: 60, priority: 'low', warmup_feeder_sets: 0 },
      { id: 'l6', template_id: 'template_lower_a', exercise_id: 'plank_o_cable_woodchopper', order_index: 6, target_sets: 3, target_reps_min: 30, target_reps_max: 45, target_rir: 1, target_rest_sec: 60, priority: 'low', warmup_feeder_sets: 0 },
    ]
  },
  {
    id: 'template_upper_b',
    name: 'Upper B (Torso Amplitud Dorsal & Pecho Medio)',
    code: 'upper_b',
    sequence_order: 3,
    target_focus: 'Dorsal Ancho, Pecho Medio, Grosor de Brazos y Deltoide',
    estimated_duration_min: 55,
    description: 'Enfocado en la silueta en V con jalones y remos con énfasis en dorsales y braquial.',
    warmup_cardio_min: 5,
    warmup_mobility: 'Rotaciones torácicas dinámicas y activación de manguito rotador con mancuerna de 2kg.',
    exercises: [
      { id: 'ub1', template_id: 'template_upper_b', exercise_id: 'press_plano_mancuernas', order_index: 1, target_sets: 3, target_reps_min: 8, target_reps_max: 12, target_rir: 2, target_rest_sec: 150, priority: 'high', warmup_feeder_sets: 2, special_notes: '2 series de aproximación progresiva.' },
      { id: 'ub2', template_id: 'template_upper_b', exercise_id: 'remo_polea_baja_neutro', order_index: 2, target_sets: 3, target_reps_min: 8, target_reps_max: 12, target_rir: 2, target_rest_sec: 120, priority: 'high', warmup_feeder_sets: 1 },
      { id: 'ub3', template_id: 'template_upper_b', exercise_id: 'pullover_polea_alta', order_index: 3, target_sets: 3, target_reps_min: 10, target_reps_max: 15, target_rir: 1, target_rest_sec: 90, priority: 'medium', warmup_feeder_sets: 0 },
      { id: 'ub4', template_id: 'template_upper_b', exercise_id: 'elevaciones_laterales_polea', order_index: 4, target_sets: 3, target_reps_min: 10, target_reps_max: 15, target_rir: 1, target_rest_sec: 90, priority: 'high', warmup_feeder_sets: 0, special_notes: 'Segundo estímulo semanal para hombros 3D.' },
      { id: 'ub5', template_id: 'template_upper_b', exercise_id: 'triceps_pushdown_polea_cuerda', order_index: 5, target_sets: 3, target_reps_min: 10, target_reps_max: 15, target_rir: 1, target_rest_sec: 90, priority: 'low', warmup_feeder_sets: 0 },
      { id: 'ub6', template_id: 'template_upper_b', exercise_id: 'curl_martillo_mancuernas', order_index: 6, target_sets: 3, target_reps_min: 10, target_reps_max: 12, target_rir: 2, target_rest_sec: 90, priority: 'low', warmup_feeder_sets: 0 },
    ]
  },
  {
    id: 'template_lower_b',
    name: 'Lower B (Pierna Unilateral & Detalle Muscular)',
    code: 'lower_b',
    sequence_order: 4,
    target_focus: 'Sentadilla Búlgara, Curles Femorales, Extensión y Core',
    estimated_duration_min: 50,
    description: 'Corrige asimetrías y maximiza el aislamiento de cuádriceps y cadena posterior.',
    warmup_cardio_min: 5,
    warmup_mobility: 'Balanceos de pierna frontal/lateral y puentes de glúteo corporales dinámicos.',
    exercises: [
      { id: 'lb1', template_id: 'template_lower_b', exercise_id: 'sentadilla_bulgara_mancuernas', order_index: 1, target_sets: 3, target_reps_min: 8, target_reps_max: 10, target_rir: 2, target_rest_sec: 120, priority: 'high', warmup_feeder_sets: 1, special_notes: '1 serie sin peso solo corporal para calibrar equilibrio.' },
      { id: 'lb2', template_id: 'template_lower_b', exercise_id: 'curl_femoral_tumbado', order_index: 2, target_sets: 3, target_reps_min: 10, target_reps_max: 12, target_rir: 1, target_rest_sec: 90, priority: 'high', warmup_feeder_sets: 0 },
      { id: 'lb3', template_id: 'template_lower_b', exercise_id: 'extension_piernas_maquina', order_index: 3, target_sets: 3, target_reps_min: 10, target_reps_max: 15, target_rir: 1, target_rest_sec: 90, priority: 'medium', warmup_feeder_sets: 0 },
      { id: 'lb4', template_id: 'template_lower_b', exercise_id: 'elevacion_talones_gemelos', order_index: 4, target_sets: 3, target_reps_min: 12, target_reps_max: 15, target_rir: 1, target_rest_sec: 60, priority: 'low', warmup_feeder_sets: 0 },
      { id: 'lb5', template_id: 'template_lower_b', exercise_id: 'elevacion_piernas_colgado_o_banco', order_index: 5, target_sets: 3, target_reps_min: 10, target_reps_max: 15, target_rir: 1, target_rest_sec: 60, priority: 'low', warmup_feeder_sets: 0 },
    ]
  }
];

export const ALTERNATIVES_MAP: Record<string, { altId: string; reason: string }[]> = {
  press_inclinado_mancuernas: [
    { altId: 'press_plano_mancuernas', reason: 'Si el banco ajustable está ocupado o hay molestia en la articulación clavicular.' }
  ],
  press_plano_mancuernas: [
    { altId: 'press_inclinado_mancuernas', reason: 'Alternativa directa de empuje pectoral si el banco plano está ocupado.' }
  ],
  remo_mancuerna_pecho_apoyado: [
    { altId: 'remo_polea_baja_neutro', reason: 'Excelente alternativa con polea si los bancos inclinados están ocupados.' }
  ],
  remo_polea_baja_neutro: [
    { altId: 'remo_mancuerna_pecho_apoyado', reason: 'Tirón horizontal con mancuernas si las poleas están ocupadas.' }
  ],
  jalon_pecho_agarre_neutro: [
    { altId: 'pullover_polea_alta', reason: 'Aísla dorsales sin involucrar bíceps si hay sobrecarga o fatiga en brazos.' }
  ],
  pullover_polea_alta: [
    { altId: 'jalon_pecho_agarre_neutro', reason: 'Tirón vertical para amplitud dorsal si buscas mayor sobrecarga con flexión de codo.' }
  ],
  elevaciones_laterales_polea: [
    { altId: 'press_inclinado_mancuernas', reason: 'Empuje con fuerte reclutamiento de hombro frontal y lateral si no hay poleas libres.' }
  ],
  curl_biceps_inclinado: [
    { altId: 'curl_martillo_mancuernas', reason: 'Menor estrés en el tendón bicipital distal.' }
  ],
  curl_martillo_mancuernas: [
    { altId: 'curl_biceps_inclinado', reason: 'Alternativa en banco inclinado para mayor estiramiento de la cabeza larga del bíceps.' }
  ],
  extension_triceps_overhead_polea: [
    { altId: 'triceps_pushdown_polea_cuerda', reason: 'Alternativa segura si falta movilidad de hombro para extender overhead.' }
  ],
  triceps_pushdown_polea_cuerda: [
    { altId: 'extension_triceps_overhead_polea', reason: 'Variante overhead para enfocar la cabeza larga en estiramiento profundo.' }
  ],
  prensa_piernas_45: [
    { altId: 'sentadilla_bulgara_mancuernas', reason: 'Permite alto estímulo con mancuernas si la prensa está ocupada.' }
  ],
  sentadilla_bulgara_mancuernas: [
    { altId: 'prensa_piernas_45', reason: 'Máxima estabilidad guiada en prensa para cuádriceps sin requerir equilibrio.' }
  ],
  peso_muerto_rumano_mancuernas: [
    { altId: 'curl_femoral_tumbado', reason: 'Aísla isquiosurales sin fatiga de agarre o lumbar si hay molestia.' }
  ],
  curl_femoral_tumbado: [
    { altId: 'peso_muerto_rumano_mancuernas', reason: 'Cadena posterior completa con mancuernas si la máquina de femoral está ocupada.' }
  ],
  extension_piernas_maquina: [
    { altId: 'prensa_piernas_45', reason: 'Patrón de extensión de rodilla con alto reclutamiento de cuádriceps.' }
  ],
  elevacion_talones_gemelos: [
    { altId: 'prensa_piernas_45', reason: 'Se puede ejecutar apoyando la punta de los pies en el borde de la prensa.' }
  ],
  plank_o_cable_woodchopper: [
    { altId: 'elevacion_piernas_colgado_o_banco', reason: 'Variante dinámica de flexión de cadera para recto abdominal inferior.' }
  ],
  elevacion_piernas_colgado_o_banco: [
    { altId: 'plank_o_cable_woodchopper', reason: 'Resistencia isométrica antirrotacional para compactar el core.' }
  ]
};

export const WARMUP_MOBILITY_ASSETS = {
  arm_circles: {
    title: 'Apertura Dinámica de Pecho y Hombros',
    desc: 'Apertura amplia de brazos hacia atrás y adelante para activar el pectoral y deltoides anterior con máxima irrigación.',
    gif: 'https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/1271.gif',
    cue: 'Abre los brazos en cruz sintiendo cómo se expande la caja torácica de forma rítmica y controlada.'
  },
  scapular_retractions: {
    title: 'Retracciones Escapulares en Plancha (Scapula Push-ups)',
    desc: 'En posición de plancha, junta y separa los omóplatos sin flexionar los codos para activar el serrato anterior y trapecio.',
    gif: 'https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/3021.gif',
    cue: 'Brazos completamente rectos. El movimiento nace exclusivamente del deslizamiento de las escápulas.'
  },
  thoracic_rotation: {
    title: 'Rotación Torácica Dinámica (World’s Greatest Stretch)',
    desc: 'En zancada baja, apoya una mano en el suelo y gira el torso abriendo el brazo contrario hacia el techo.',
    gif: 'https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/1604.gif',
    cue: 'Gira el pecho siguiendo tu mano con la mirada para rotar desde la columna torácica, no lumbar.'
  },
  ankle_mobility: {
    title: 'Movilidad de Tobillo y Pantorrilla en Pared (Dorsiflexión)',
    desc: 'Manos en la pared, empuja la rodilla hacia adelante sin despegar el talón del suelo para desbloquear el tobillo.',
    gif: 'https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/1407.gif',
    cue: 'Talón clavado al piso como si tuviera pegamento mientras la rodilla avanza hacia la pared.'
  },
  hip_90_90: {
    title: 'Apertura Profunda de Cadera y Aductores (Frog Stretch)',
    desc: 'En cuadrupedia con rodillas separadas, balancea la cadera suavemente hacia atrás sintiendo los aductores.',
    gif: 'https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/2571.gif',
    cue: 'Abre las rodillas a una anchura cómoda y lleva los glúteos hacia los talones con suavidad.'
  },
  goblet_squat_hold: {
    title: 'Sentadilla Profunda Isométrica (Deep Squat Hold)',
    desc: 'Mantén la posición profunda de sentadilla con el pecho erguido y las rodillas abiertas hacia afuera.',
    gif: 'https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets/3119.gif',
    cue: 'Talones en el piso, pecho alto y abre las rodillas en la misma línea de la punta de los pies.'
  }
};
